### ISSUE TITLE
ユーザのtime_logs変更の際のエラー文言

### ISSUE THREAD

**Issue by shimojik** [ShimojiK/clockin#2]
ユーザがtime_logsを変更するとき、スタートした時間より前を設定した場合、「更新に失敗しました」と表示されるんですが、これが何で失敗したのかが分からないので、文言を変更したほうがいいと思います！

**Comment by techno-tanoC** [comment]
https://github.com/ShimojiK/clockin/commit/c081654a042b20513d6abf83414aea2c55db3c88 により修正しました。

**Comment by shimojik** [comment]
![LGTM](http://lgtm.in/p/gocX95B9q)
